Resources:

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://my-bucket-2024-05-30-new/scripts/glue-script.py
      DefaultArguments:
        "--TempDir": "s3://my-bucket-2024-05-30-new/template/"
      GlueVersion: "2.0"
      WorkerType: G.1X
      NumberOfWorkers: 3
      DefaultArguments:
        "--extra-jars": "s3://my-bucket-2024-05-30-new/scripts/moduleslib.zip"


  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-MyRoleForGlue"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
